### PR TITLE
Fix issue with in-app browser closing on app re-entry

### LINKED ISSUE #27: In-app browser closes on app re-entry
On the first start of the app, one has to log in to an account, either to one hosted at Netbird itself or to a self-hosted one. Now as I use a password manager I have to temporarily switch the app to grab the user credentials. However, when I re-enter the Netbird Android app to paste the credentials, the in-app browser closes instantaneously.

### PR DESCRIPTION
**Pull request by mineiwik**
Fixes #27

### CODE REVIEW

**Review by pappz — APPROVED** [review]

**Comment by pappz** [comment]
Hello @mineiwik 

Looks like your PR caused a new issue for some users. Could you take a look to [this](https://github.com/netbirdio/android-client/issues/40#issuecomment-2627545993) thread?

**Comment by mineiwik** [comment]
Hi @pappz 

I think the issue you referenced is more related to [this](https://github.com/golang/go/issues/70508) issue and caused by a newer Go version which will crash on systems with Android versions below 12.

**Comment by pappz** [comment]
That you mentioned is could be a valid issue. Nevertheless, I prepared an APK without your fix and the feedback is the app does not crash. This is why I think we should look for the root cause of the issue somewhere here.

**Comment by mineiwik** [comment]
@pappz 

Since Go version 1.23.5 (released 3 weeks ago) the issue should have been [resolved](https://github.com/golang/go/commit/9563300f6e262589ae25c71d778bfcd646d4a750). Maybe it's worth a try to compile everything again (using Go 1.23.5) from the master branch (without changing anything) to check if the issue still persists. I don't want to say that my PR is fully correct, I just cannot find anything that could cause the issues reported.

Thanks

**Comment by pappz** [comment]
Good point! I will do.
Why did you change your answer? I mean I like to step forward to a newer version instead of back :)

**Comment by mineiwik** [comment]
@pappz 

I have seen that the problem may still persist on the newer versions especially when gomobile is being used, but versions before 1.23.0 should not have this specific issue.

**Pull request merged**
